# Generated by Django 5.1.3 on 2024-11-29 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Kids', 'Kids'), ('Women', 'Women'), ('Men', 'Men'), ('Winter Collection', 'Winter Collection'), ('Summer Collection', 'Summer Collection')], max_length=50),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
