# Generated by Django 5.2 on 2025-04-17 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_order_address_order_payment_method_order_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Kids', 'Kids'), ('Women', 'Women'), ('Men', 'Men'), ('Thrifting Clothes', 'Thrifting Clothes'), ('Summer Collection', 'Summer Collection')], max_length=50),
        ),
    ]
